<?php

namespace AppBundle\Repository;

/**
 * LetterConfigurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LetterConfigurationRepository extends \Doctrine\ORM\EntityRepository
{
}
