<?php

namespace AppBundle\Repository;

/**
 * ScoresheetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScoresheetRepository extends \Doctrine\ORM\EntityRepository
{
}
