# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.reconstruction:
        class:     AppBundle\Reconstruction\Reconstruction
#        arguments: ["@service_id", "plain_value", "%parameter%"]

