# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.available_tiles_generator:
      class:    AppBundle\Reconstruction\AvailableTilesGenerator
    app.reconstruction:
        class:     AppBundle\Reconstruction\Reconstruction
        arguments: ["@app.available_tiles_generator"]

